apiVersion: v1
kind: ConfigMap
metadata:
 name: mongodb-conf
 namespace: m-ecommerce
data:
 host: mongodb-service
 port: "27017"
---

apiVersion: v1
kind: Secret
metadata:
 name: jwt-secret
 namespace: m-ecommerce
data:
 token_key: MTMyMTMyNAo=



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: m-ecommerce
spec:
  selector:
    matchLabels:
      app: gateway-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-deployment
    spec:
      containers:
        - name: gateway-deployment
          image: asmaeel/gateway-microservice:1.0
          ports:
            - containerPort: 5005
              name: gateway-port
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongodb-conf
                  key: host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongodb-conf
                  key: port
            - name: MONGO_URI
              value: "mongodb://mongodb-service/microservices"
            - name: ORDERS_SERVER
              value: "http://order-service:5002/api"
            - name: PRODUCTS_SERVER
              value: "http://product-service:5001/api"
            - name: PAYMENT_SERVER
              value: "http://payment-service:5003/api"
            - name: JWT-Secret
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: token_key